### ISSUE TITLE
Not loading modern theme

### ISSUE THREAD

**Issue by blitux** [raulfraile/ladybug#67]
Hi to all, 

I've downloaded master and 1.0.11, and it doesn't load modern theme, just the basic styles. I've searched on the docs and googled about the issue, without results, just one drupal user describing the same issue here: https://www.drupal.org/node/2383765

**Comment by josgilmo** [comment]
It's work, but is not very well documented. 

Writing this, at the beginning of your execution and it must work:

ladybug_set_theme("modern");

**Comment by DeeJaVu** [comment]
it works like this

$dumper = new \Ladybug\Dumper();
$dumper->setTheme("modern");

echo $dumper->dump($myVar);

---------------------------------------

also look at the source code its very well documented
https://github.com/raulfraile/ladybug/blob/master/src/Ladybug/Dumper.php

**Comment by blitux** [comment]
Hello, thanks! I was supposing the theme was being set on the instantiation by default, as the docs didn't say nothing about one having to explicitly set the theme.

**Comment by DeeJaVu** [comment]
here https://github.com/raulfraile/ladybug/blob/master/doc/usage.md
look at the configuration section

**Comment by blitux** [comment]
Yes, indeed. But I interpreted that as the posibility to change the theme, not that you MUST set it for it to work. But, again, that's me.

Thank you very much!
