### ISSUE TITLE
Unknown "render_type" function in layout.html.twig at line 29.

### ISSUE THREAD

**Issue by arnaud-lb** [raulfraile/ladybug#74]
It seems that commit c6d86d7f2081e5fc730887818aabab1d8e175acb introduced a bug causing fatal errors when trying to use ladybug:

    Unknown "render_type" function in layout.html.twig at line 29.

I think that Twig_SimpleFunction takes the user-side function name as first parameter, and that keys are ignored in the array returned by getFunctions().

**Comment by younes0** [comment]
@arnaud-lb désolé :/

**Comment by arnaud-lb** [comment]
@younes0 @raulfraile merci :)
